apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.DeploymentName }}
  labels: 
    app: {{ .Values.DeploymentName }}
    team: {{ .Values.Team }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ .Chart.Name }}
    environment-tag: {{ .Values.EnvironmentTag }}
spec:
  replicas: {{ .Values.ReplicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.DeploymentName }}
  template:
    metadata:
      labels:
        app: {{ .Values.DeploymentName }}
    spec:
      containers:
      - name: {{ .Values.DeploymentName }}-container
        image: conplementag/browserstack-local:latest
        command: ["/usr/local/bin/BrowserStackLocal"]
        args: ["{{ .Values.Browserstack_AccessToken }}", "--verbose", "2", "--force-local", "--enable-logging-for-api", "--only-automate", "--local-identifier", "{{ .Values.Browserstack_Local_Identifier }}"]
        resources:
          requests:
            memory: {{ .Values.RequestsMemory }}
            cpu: {{ .Values.RequestsCpu }}
          limits:
            memory: {{ .Values.LimitsMemory }}
            cpu: {{ .Values.LimitsCpu }}  
